version: '3'
services:
  node_app:
    image: node:alpine
    container_name: my_node_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    tty: true
    depends_on:
      - mongodb
      - redis
    networks:
      - my_network

  mongodb:
    image: mongo
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./project/mongodb-backup:/data/db
    networks:
      my_network:
        ipv4_address: 172.28.0.2

  redis:
    image: redis
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      my_network:
        ipv4_address: 172.28.0.3

volumes:
  mongodb_data:
  redis_data:

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16