version: '3'
services:
  node_app:
    image: node:alpine
    container_name: my_node_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    tty: true
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./project/mongodb-backup:/data/db

volumes:
  mongodb_data:
